using System;
using MobaVR.ClassicModeStateMachine;
using Photon.Pun;
using UnityEngine;

namespace MobaVR
{
    [Serializable]
    public class BaseStateMachine<T> : MonoBehaviourPun, IClassicModeState where T : GameMode<T>
    {
        [Header("States")]
        [SerializeField] protected ModeState<T> m_InitModeState;
        [SerializeField] protected ModeState<T> m_InactiveModeState;
        [SerializeField] protected ModeState<T> m_StartModeState;
        [SerializeField] protected ModeState<T> m_ReadyRoundState;
        [SerializeField] protected ModeState<T> m_PlayRoundState;
        [SerializeField] protected ModeState<T> m_CompleteRoundState;
        [SerializeField] protected ModeState<T> m_CompleteModeState;

        [Header("Current State")]
        [SerializeField] protected bool m_IsInitOnAwake = true;
        [SerializeField] protected ClassicModeState m_ModeState = ClassicModeState.MODE_INACTIVE;
        [SerializeField] protected ModeState<T> m_CurrentState;

        protected ClassicMode m_Mode;

        public event Action<ModeState<T>> OnStateChanged;

        public ModeState<T> CurrentState => m_CurrentState;
        public ModeState<T> InactiveModeState => m_InactiveModeState;
        public ModeState<T> InitModeState => m_InitModeState;
        public ModeState<T> StartModeState => m_StartModeState;
        public ModeState<T> ReadyRoundState => m_ReadyRoundState;
        public ModeState<T> PlayRoundState => m_PlayRoundState;
        public ModeState<T> CompleteRoundState => m_CompleteRoundState;
        public ModeState<T> CompleteModeState => m_CompleteModeState;
        public ClassicModeState ModeState => m_ModeState;
        public ClassicMode Mode => m_Mode;

        /*
        public StateMachine(ClassicMode mode)
        {
            Init(mode);
        }
        */

        private void Update()
        {
            if (CurrentState != null)
            {
                CurrentState.Update();
            }
        }

        public void Init(T mode)
        {
            m_InitModeState.Init(mode, this);
            m_InactiveModeState.Init(mode, this);
            m_StartModeState.Init(mode, this);
            m_ReadyRoundState.Init(mode, this);
            m_PlayRoundState.Init(mode, this);
            m_CompleteRoundState.Init(mode, this);
            m_CompleteModeState.Init(mode, this);

            if (m_IsInitOnAwake)
            {
                //RpcDeactivateMode();
                DeactivateMode();
            }
        }

        public void SetState(ModeState<T> nextState)
        {
            if (CurrentState != null)
            {
                CurrentState.Exit();
            }

            m_CurrentState = nextState;
            nextState.Enter();
            OnStateChanged?.Invoke(nextState);
        }

        public void InitMode()
        {
            if (PhotonNetwork.IsMasterClient)
            {
                photonView.RPC(nameof(RpcInitMode), RpcTarget.AllBuffered);
            }
        }

        [PunRPC]
        protected void RpcInitMode()
        {
            m_ModeState = ClassicModeState.MODE_INIT;
            SetState(m_InitModeState);
        }

        public void DeactivateMode()
        {
            //if (PhotonNetwork.IsMasterClient)
            {
                photonView.RPC(nameof(RpcDeactivateMode), RpcTarget.AllBuffered);
            }
        }

        [PunRPC]
        protected void RpcDeactivateMode()
        {
            m_ModeState = ClassicModeState.MODE_INACTIVE;
            SetState(m_InactiveModeState);
        }

        public void StartMode()
        {
            if (PhotonNetwork.IsMasterClient)
            {
                photonView.RPC(nameof(RpcStartMode), RpcTarget.AllBuffered);
            }
        }

        [PunRPC]
        protected void RpcStartMode()
        {
            m_ModeState = ClassicModeState.MODE_START;
            SetState(m_StartModeState);
        }

        public void ReadyRound()
        {
            if (PhotonNetwork.IsMasterClient)
            {
                photonView.RPC(nameof(RpcReadyRound), RpcTarget.AllBuffered);
            }
        }

        [PunRPC]
        protected void RpcReadyRound()
        {
            m_ModeState = ClassicModeState.ROUND_READY;
            SetState(m_ReadyRoundState);
        }

        public void PlayRound()
        {
            if (PhotonNetwork.IsMasterClient)
            {
                photonView.RPC(nameof(RpcPlayRound), RpcTarget.AllBuffered);
            }
        }

        [PunRPC]
        protected void RpcPlayRound()
        {
            m_ModeState = ClassicModeState.ROUND_PLAY;
            SetState(m_PlayRoundState);
        }

        public void CompleteRound()
        {
            if (PhotonNetwork.IsMasterClient)
            {
                photonView.RPC(nameof(RpcCompleteRound), RpcTarget.AllBuffered);
            }
        }

        [PunRPC]
        protected void RpcCompleteRound()
        {
            m_ModeState = ClassicModeState.ROUND_COMPLETE;
            SetState(m_CompleteRoundState);
        }

        public void CompleteMode()
        {
            if (PhotonNetwork.IsMasterClient)
            {
                photonView.RPC(nameof(RpcCompleteMode), RpcTarget.AllBuffered);
            }
        }

        [PunRPC]
        protected void RpcCompleteMode()
        {
            m_ModeState = ClassicModeState.MODE_COMPLETE;
            SetState(m_CompleteModeState);
        }
    }
}